name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022, macos-14]
        node-version: ['18.x']
        test-command:
          - npm run test-style
          - npm run test-types
          - npm run test-unit
          - npm run test-macos-key-press
        exclude:
          # The `test-style` script is platform-independent, so there is no
          # value in executing it in multiple operating systems.
          - os: macos-14
            test-command: npm run test-style
          # The `test-types` script is platform-independent, so there is no
          # value in executing it in multiple operating systems.
          - os: macos-14
            test-command: npm run test-types
          # The `test-macos-key-press` script exercises macOS platform code,
          # making it inappropriate for Windows environments.
          - os: windows-2022
            test-command: npm run test-macos-key-press

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: ${{ matrix.test-command }}
